[project]
name = "synthetic-speech-data-pipeline-for-stt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataset>=2.0.0",
    "datasets>=4.8.5",
    "dotenv>=0.9.9",
    "google-genai>=2.0.1",
    "gradio>=6.14.0",
    "hf>=1.14.0",
    "jiwer>=4.0.0",
    "langchain>=1.2.18",
    "langchain-google-genai>=3.2.0",
    "librosa>=0.11.0",
    "loguru>=0.7.3",
    "numpy>=2.4.4",
    "pandas>=3.0.3",
    "pydub>=0.25.1",
    "scipy>=1.17.1",
    "soundfile>=0.13.1",
]
